# Generated by Django 5.2.5 on 2025-08-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoilType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="British Soil Classification System name (e.g., 'Well-graded Gravel (GW)')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on soil characteristics (e.g., 'Free-draining, high strength')",
                    ),
                ),
                (
                    "unit_weight_dry_min",
                    models.FloatField(
                        help_text="Typical minimum dry unit weight (kN/m^3)"
                    ),
                ),
                (
                    "unit_weight_dry_max",
                    models.FloatField(
                        help_text="Typical maximum dry unit weight (kN/m^3)"
                    ),
                ),
                (
                    "unit_weight_saturated_min",
                    models.FloatField(
                        help_text="Typical minimum saturated unit weight (kN/m^3)"
                    ),
                ),
                (
                    "unit_weight_saturated_max",
                    models.FloatField(
                        help_text="Typical maximum saturated unit weight (kN/m^3)"
                    ),
                ),
                (
                    "phi_k_min",
                    models.FloatField(
                        help_text="Characteristic minimum angle of shearing resistance (phi_k') in degrees"
                    ),
                ),
                (
                    "phi_k_max",
                    models.FloatField(
                        help_text="Characteristic maximum angle of shearing resistance (phi_k') in degrees"
                    ),
                ),
                (
                    "c_k_min",
                    models.FloatField(
                        help_text="Characteristic minimum effective cohesion (c_k') in kPa"
                    ),
                ),
                (
                    "c_k_max",
                    models.FloatField(
                        help_text="Characteristic maximum effective cohesion (c_k') in kPa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurchargeLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for the surcharge load (e.g., 'Flat Garden/Lawn (Light Load)')",
                        max_length=255,
                    ),
                ),
                (
                    "pressure",
                    models.FloatField(
                        help_text="Equivalent uniform pressure (q) in kN/m^2"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WallMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the construction material (e.g., 'Mass / Reinforced Concrete')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "unit_weight_min",
                    models.FloatField(
                        help_text="Typical minimum unit weight (gamma) in kN/m^3"
                    ),
                ),
                (
                    "unit_weight_max",
                    models.FloatField(
                        help_text="Typical maximum unit weight (gamma) in kN/m^3"
                    ),
                ),
            ],
        ),
    ]
