# Generated by Django 5.2.5 on 2025-08-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoilType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for the soil type (e.g., 'Sandy Gravel (Good Drainage)')",
                        max_length=255,
                    ),
                ),
                (
                    "angle_of_internal_friction",
                    models.FloatField(
                        help_text="Angle of internal friction (phi) in degrees"
                    ),
                ),
                (
                    "soil_density",
                    models.FloatField(
                        help_text="Density of the soil (gamma) in kN/m^3"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurchargeLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for the surcharge load (e.g., 'Flat Garden/Lawn (Light Load)')",
                        max_length=255,
                    ),
                ),
                (
                    "pressure",
                    models.FloatField(
                        help_text="Equivalent uniform pressure (q) in kN/m^2"
                    ),
                ),
            ],
        ),
    ]
