# Generated by Django 5.2.5 on 2025-08-18 11:48

from django.db import migrations

SOIL_TYPES_DATA = [
    {
        "name": "Well-graded Gravel (GW)",
        "notes": "Free-draining, high strength",
        "unit_weight_dry_min": 19.0, "unit_weight_dry_max": 22.0,
        "unit_weight_saturated_min": 21.0, "unit_weight_saturated_max": 23.0,
        "phi_k_min": 36.0, "phi_k_max": 40.0,
        "c_k_min": 0.0, "c_k_max": 0.0,
    },
    {
        "name": "Poorly-graded Sand (SP)",
        "notes": "Free-draining, good strength",
        "unit_weight_dry_min": 17.0, "unit_weight_dry_max": 20.0,
        "unit_weight_saturated_min": 19.0, "unit_weight_saturated_max": 22.0,
        "phi_k_min": 30.0, "phi_k_max": 35.0,
        "c_k_min": 0.0, "c_k_max": 0.0,
    },
    {
        "name": "Silty Sand (SM)",
        "notes": "Lower permeability, susceptible to frost",
        "unit_weight_dry_min": 18.0, "unit_weight_dry_max": 21.0,
        "unit_weight_saturated_min": 20.0, "unit_weight_saturated_max": 22.0,
        "phi_k_min": 28.0, "phi_k_max": 32.0,
        "c_k_min": 0.0, "c_k_max": 5.0,
    },
    {
        "name": "Clayey Sand (SC)",
        "notes": "Low permeability, some cohesion",
        "unit_weight_dry_min": 18.0, "unit_weight_dry_max": 21.0,
        "unit_weight_saturated_min": 20.0, "unit_weight_saturated_max": 23.0,
        "phi_k_min": 26.0, "phi_k_max": 30.0,
        "c_k_min": 5.0, "c_k_max": 10.0,
    },
    {
        "name": "Silt (Low Plasticity, ML)",
        "notes": "Low permeability, can lose strength when wet",
        "unit_weight_dry_min": 17.0, "unit_weight_dry_max": 20.0,
        "unit_weight_saturated_min": 19.0, "unit_weight_saturated_max": 21.0,
        "phi_k_min": 26.0, "phi_k_max": 30.0,
        "c_k_min": 0.0, "c_k_max": 10.0,
    },
    {
        "name": "Clay (Low Plasticity, CL)",
        "notes": "Low shrink-swell potential, poor drainage",
        "unit_weight_dry_min": 17.0, "unit_weight_dry_max": 19.0,
        "unit_weight_saturated_min": 19.0, "unit_weight_saturated_max": 21.0,
        "phi_k_min": 24.0, "phi_k_max": 28.0,
        "c_k_min": 5.0, "c_k_max": 10.0,
    },
    {
        "name": "Clay (High Plasticity, CH)",
        "notes": "High shrink-swell potential, very poor drainage",
        "unit_weight_dry_min": 16.0, "unit_weight_dry_max": 18.0,
        "unit_weight_saturated_min": 18.0, "unit_weight_saturated_max": 20.0,
        "phi_k_min": 18.0, "phi_k_max": 22.0,
        "c_k_min": 10.0, "c_k_max": 20.0,
    },
]

WALL_MATERIALS_DATA = [
    {"name": "Mass / Reinforced Concrete", "unit_weight_min": 24.0, "unit_weight_max": 24.0},
    {"name": "Dense Concrete Blocks", "unit_weight_min": 20.0, "unit_weight_max": 23.0},
    {"name": "Medium Dense Concrete Blocks", "unit_weight_min": 14.0, "unit_weight_max": 16.0},
    {"name": "Natural Stone (Granite)", "unit_weight_min": 25.5, "unit_weight_max": 26.5},
    {"name": "Natural Stone (Sandstone)", "unit_weight_min": 21.5, "unit_weight_max": 23.5},
    {"name": "Gabion Fill (Stone with voids)", "unit_weight_min": 17.0, "unit_weight_max": 19.0},
    {"name": "Timber (Oak - Hardwood)", "unit_weight_min": 8.5, "unit_weight_max": 12.0},
    {"name": "Timber (Pine - Softwood)", "unit_weight_min": 5.5, "unit_weight_max": 6.5},
]

def populate_initial_data(apps, schema_editor):
    """
    Populates the database with initial soil types and wall materials.
    """
    SoilType = apps.get_model('calculator', 'SoilType')
    WallMaterial = apps.get_model('calculator', 'WallMaterial')

    for data in SOIL_TYPES_DATA:
        SoilType.objects.create(**data)

    for data in WALL_MATERIALS_DATA:
        WallMaterial.objects.create(**data)

def delete_initial_data(apps, schema_editor):
    """
    Deletes the initial data.
    """
    SoilType = apps.get_model('calculator', 'SoilType')
    WallMaterial = apps.get_model('calculator', 'WallMaterial')

    soil_names = [d['name'] for d in SOIL_TYPES_DATA]
    SoilType.objects.filter(name__in=soil_names).delete()

    material_names = [d['name'] for d in WALL_MATERIALS_DATA]
    WallMaterial.objects.filter(name__in=material_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_code=delete_initial_data),
    ]
