# Generated by Django 5.2.5 on 2025-08-14 04:13

from django.db import migrations

def populate_initial_data(apps, schema_editor):
    """
    Populates the database with initial soil types and surcharge loads.
    """
    SoilType = apps.get_model('calculator', 'SoilType')
    SurchargeLoad = apps.get_model('calculator', 'SurchargeLoad')
    db_alias = schema_editor.connection.alias

    # Soil Types from project brief
    SoilType.objects.using(db_alias).bulk_create([
        SoilType(name="Sandy Gravel (Good Drainage)", angle_of_internal_friction=35, soil_density=18),
        SoilType(name="Silty Clay (Average Drainage)", angle_of_internal_friction=30, soil_density=19), # Assumed values
        SoilType(name="Heavy, Wet Clay (Poor Drainage)", angle_of_internal_friction=25, soil_density=20),
    ])

    # Surcharge Loads from project brief
    SurchargeLoad.objects.using(db_alias).bulk_create([
        SurchargeLoad(name="Flat Garden/Lawn (Light Load)", pressure=0), # Assumed 0 for light
        SurchargeLoad(name="Sloped Garden (Medium Load)", pressure=5), # Assumed 5 for medium
        SurchargeLoad(name="Driveway/Patio (Heavy Load)", pressure=10),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
